version: '3'

volumes:
  moloch:
    driver: local
  esdata:
    driver: local

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    environment:
      - discovery.type=single-node
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
  moloch:
    privileged: true
    build:
       context: .
    image: dwesthuis/moloch-2.3.1
    environment:
      - INITALIZEDB=true
      - MOLOCH_PASSWORD=CHANGE_PASSWORD!!
      - SMB_USER=CHANGE_SMB_USERNAME!!
      - SMB_PASSWORD=CHANGE_SMB_PASSWORD!!
      - SMB_DOMAIN=CHANGE_SMB_DOMAIN!!
      - SMB_SHARE=CHANGE_SMB_SHARE!!
      - WIPEDB=false
      - MOLOCH_VERSION=2.3.0-1_amd64
      - UBUNTU_VERSION=18.04
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - MOLOCH_INTERFACE=eth0
      - CAPTURE=off
      - VIEWER=on
      - CRON=on
      - SMB=on
    depends_on:
      - elasticsearch
    ports:
      - 0.0.0.0:8005:8005
    volumes:
      - ./pcap:/data/pcap
      - ./etc:/data/moloch/etc
      - ./logs:/data/moloch/logs
      - ./raw:/data/moloch/raw
      - moloch:/data/configured
